
title: Kuku language
author:
  name: Alexander Tuzhik
  email: alprog@hotmail.com
description:
  Scripting language and data format designed 
  for data-intensive video games and modding friendly
baseurl: "/kuku"
url: "https://alprog.github.io"

plugins:
  - jekyll-feed

minima:
  skin: solarized-dark

  social_links:
      twitter: kuku_language
      github: kuku