#pragma once

#include "reflectable_enum.h"

Reflectable_enum(Token_type,
    Bool_literal,
    Integer_literal,
    Number_literal,
    String_literal,
    Unclosed_string_literal,
    Assign_operator,
    Plus_sign,
    Operator,
    Open_bracket,
    Close_bracket,
    Open_brace,
    Close_brace,
    Open_chevron,
    Close_chevron,
    Open_parenthesis,
    Close_parenthesis,
    Identifier,
    Colon,
    Semicolon,
    Dot,
    Comma,
    End_of_line,
    End_of_source,
    Comment,

    Keyword_and,
    Keyword_class,
    Keyword_do,
    Keyword_else,
    Keyword_end,
    Keyword_for,
    Keyword_function,
    Keyword_or,
    Keyword_then,
    Keyword_var,
    Keyword_while
);